services:
  - type: web
    name: chatbot-mvp-python
    env: python
    buildCommand: pip install -r requirements.txt -c constraints.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
